### ISSUE TITLE
Add translation in English

### ISSUE THREAD

**Issue by 7ORP3DO** [my-happy-team/join-us#13]
Hii @MohammedChaker,  Can I create a new readme file in english so that even those who don't know arabic can understand it and join your organization. 

For example I don't understand Arabic so I had to use translator to understand this file. 

I would love to work on this issue.

**Comment by MohammedChaker** [comment]
yeh of cource, add translation please

**Comment by aminaNBA** [comment]
yes please it will be more Professional

**Comment by MohammedChaker** [comment]
thank you @7ORP3DO
