### ISSUE TITLE
Contact us doesn't provide any contact information

### ISSUE THREAD

**Issue by oussamakami** [my-happy-team/join-us#25]
The README file (Arabic version) doesn't contain a medium to contact the leaders of this collaboration

And the link provided with the English version leads to the profile of the organization which doesn't provide/include any valid way to reach any of the leaders

**Comment by MohammedChaker** [comment]
sorry , it's a fault , it should remove this part for README file , I mean we don't need to add contact mediums now ,we just started, need more time . 
thanks..
